version: 2
updates:
  - package-ecosystem: npm
    directory: /nuxt
    schedule:
      interval: weekly
      timezone: Asia/Tokyo
      day: sunday
    open-pull-requests-limit: 10

  - package-ecosystem: npm
    directory: /firebase/functions
    schedule:
      interval: weekly
      timezone: Asia/Tokyo
      day: sunday
    open-pull-requests-limit: 10
