version: 2
updates:
  - package-ecosystem: npm
    directory: /nuxt
    schedule:
      interval: weekly
      timezone: Asia/Tokyo
      day: sunday
    labels:
      - dependencies

  - package-ecosystem: npm
    directory: /firebase/functions
    schedule:
      interval: weekly
      timezone: Asia/Tokyo
      day: sunday
    labels:
      - dependencies
