rules:
  quotes:
    - error
    - double
  semi:
    - error
    - never
  object-curly-spacing:
    - error
    - never
  comma-dangle:
    - error
    - always-multiline
  func-call-spacing: off
  space-before-function-paren:
    - error
    - never
  no-console:
    - warn
    - allow:
        - error
  no-useless-constructor: off
  vue/multi-word-component-names: off
  vue/no-v-html: off
  import/named: off
  no-use-before-define: off