injectEnvironmentFiles:
  - packages/nuxt/.env?

nodeLinker: node-modules

compressionLevel: 0

npmScopes:
  chika3742:
    npmAuthToken: "${GITHUB_PACKAGES_TOKEN-}"
    npmRegistryServer: "https://npm.pkg.github.com"
