root: true

env:
  es2021: true

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended-type-checked
  - ../../.eslintrc.yml

parserOptions:
  project: true
  sourceType: module
  ecmaVersion: latest

ignorePatterns: []

rules:
  no-console: off
