root: true

env:
  es6: true
  node: true
  browser: false

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended-type-checked
  - ../../../.eslintrc.yml

parserOptions:
  project: true

ignorePatterns:
  - /lib/**/*
