root: true

env:
  es2021: true

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - ../.eslintrc.yml

parserOptions:
  sourceType: module
  ecmaVersion: latest

plugins:
  - "@typescript-eslint"

ignorePatterns: [ ]

rules:
  no-console: off
