root: true

env:
  es6: true
  node: true
  browser: false

overrides: []

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended-type-checked
  - ../../.eslintrc.yml

parser: "@typescript-eslint/parser"

parserOptions:
  project: true

ignorePatterns:
  - /lib/**/*
