root: true
env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:vue/vue3-essential
  - plugin:@typescript-eslint/recommended
  - "@nuxtjs/eslint-config-typescript"
overrides: []
parser: 'vue-eslint-parser'
ignorePatterns:
  - .output/**
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - vue
  - '@typescript-eslint'
rules:
  indent:
    - error
    - 2
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - never
  object-curly-spacing:
    - error
    - never
  comma-dangle:
    - error
    - always-multiline
  "@typescript-eslint/no-var-requires": off
  "@typescript-eslint/no-redeclare": off
  no-trailing-spaces: warn
  space-before-function-paren:
    - error
    - never
  "import/named": off
  "@typescript-eslint/ban-ts-comment": off
  vue/no-v-model-argument: off
  vue/multi-word-component-names: off
  "@typescript-eslint/no-non-null-assertion": off
  "@typescript-eslint/no-explicit-any": off
  vue/no-v-html: off
  func-call-spacing: off
  no-useless-constructor: off
  no-console:
    - warn
    - allow:
        - error
        - warn
  import/default: off
  import/no-named-as-default-member: off