name: "lint"

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
          cache-dependency-path: "**/yarn.lock"

      - uses: oven-sh/setup-bun@v1

      - name: bun/yarn install
        run: |
          (cd nuxt && GITHUB_PACKAGES_TOKEN="${{ secrets.MMC_PACKAGES_TOKEN }}" bun install)
          (cd algolia-sync && bun install --frozen-lockfile)
          (cd firebase/functions && yarn install --immutable)

      - name: Lint (nuxt)
        working-directory: nuxt
        run: bun lint

      - name: Lint (algolia-sync)
        working-directory: algolia-sync
        run: bun lint

      - name: Lint (firebase)
        working-directory: firebase/functions
        run: yarn lint
